### ISSUE TITLE
Assignment_week1(ready for grading)

### ISSUE THREAD

**Issue by hangsoo** [SES-5215-F2020/hjeong-quant#1]
Here are both Rmd file and html file for my first-week assignment. I look forward to your feedback!

**Comment by hangsoo** [comment]
I don't see any comment or feedback on this yet. Please let me know if there is any issue with checking my assignment!

**Comment by c-voulgaris** [comment]
There's no problem. We have 37 students in this class and we haven't finished reading/grading all the assignments yet. We appreciate your patience.

**Comment by saratepfer** [comment]
Nice job. 

**Comments on Content**
You note that it is assumed that if someone works, then that person commutes. I'm not sure this is a good assumption, as there may be a significant number of people who work from home. That being said, you filter out the non-commuters when you add the JWMNP>0 filter. I think it would be clearer to say that you are focusing on Massachusetts workers who commute.

**Comments on Code**
Line 11: To avoid cluttering your output with package messages, consider replacing this line with {r load libraries, message=FALSE}
Line 38: To avoid printing hundreds of lines of progress messages, replace this line with ``` {r, results = 'hide'}. 
Lines 48-49: You can add a filter here to remove your NA observations. %>% filter(Ten_label != "N/A (GQ/vacant)")
