### ISSUE TITLE
Assignment_week2(ready for grading)

### ISSUE THREAD

**Issue by hangsoo** [SES-5215-F2020/hjeong-quant#2]
Please refer to the rmd and the html files for grading. Many thanks in advance!

**Comment by saratepfer** [comment]
Thank you, Hangsoo! Please find comments below.

**Comments on Code**
- line 10: replace {r} with {r, message = FALSE} to prevent R from printing unnecessary messages in your markdown file. These just clutter the html.
- You can include options(scipen = 999) in the line just above your ggplot to remove the scientific notation (above line 87).

**Comments on Content**
- It looks like you didn't report/interpret the medians for your continuous variables. Please add this in.
- It would be helpful to tabulate your results for your categorical variable to make it easier for the reader to interpret. I recommend using the tibble() function for this. (Please see Catherine's example assignment.)
- Is there a reason you didn't include the calculations for your other two categorical variables? This would be helpful to include.
